from __future__ import annotations

from typing import Any


# Static catalog for UI / diagnostics. Runtime readiness is computed separately.
PROVIDER_CATALOG: list[dict[str, Any]] = [
    {
        "id": "auto",
        "name": "自动组合（推荐）",
        "cost": "free_combo",
        "cost_label": "免费组合（按可用源自动尝试）",
        "needs_user_key": False,
        "pip": ["akshare", "pandas", "yfinance"],
        "markets": ["ashare", "hk", "us", "etf", "fund"],
        "notes": "优先级：akshare → yfinance → tushare → alphavantage；失败 fail-closed。",
        "implemented": True,
    },
    {
        "id": "akshare",
        "name": "AkShare（含东财/新浪/腾讯等公开源）",
        "cost": "free",
        "cost_label": "免费（无 API Key）",
        "needs_user_key": False,
        "pip": ["akshare", "pandas"],
        "markets": ["ashare", "hk", "us", "etf", "fund"],
        "notes": "当前 A 股主力；不是东方财富官方开放平台授权 SDK。",
        "implemented": True,
    },
    {
        "id": "yfinance",
        "name": "Yahoo Finance (yfinance)",
        "cost": "free",
        "cost_label": "免费（无官方 Key，非官方接口）",
        "needs_user_key": False,
        "pip": ["yfinance"],
        "markets": ["us", "hk"],
        "notes": "美股/部分港股补充；接口可能变动。",
        "implemented": True,
    },
    {
        "id": "tushare",
        "name": "Tushare Pro",
        "cost": "freemium",
        "cost_label": "免费额度 + 积分/付费点",
        "needs_user_key": True,
        "key_env": "CAISHENFOLIO_TUSHARE_TOKEN",
        "signup_url": "https://tushare.pro",
        "pip": ["tushare"],
        "markets": ["ashare", "etf", "fund"],
        "notes": "需注册 token；积分不足时部分接口会失败（fail-closed）。",
        "implemented": True,
    },
    {
        "id": "alphavantage",
        "name": "Alpha Vantage",
        "cost": "freemium",
        "cost_label": "免费档限额 + 付费档",
        "needs_user_key": True,
        "key_env": "CAISHENFOLIO_ALPHAVANTAGE_API_KEY",
        "signup_url": "https://www.alphavantage.co/support/#api-key",
        "pip": [],
        "markets": ["us"],
        "notes": "适合美股补充；免费档有调用频率限制。",
        "implemented": True,
    },
    {
        "id": "fixture",
        "name": "本地合成演示",
        "cost": "free",
        "cost_label": "免费（合成，非真实）",
        "needs_user_key": False,
        "pip": [],
        "markets": ["demo"],
        "notes": "仅 UI/联调，禁止当作投资依据。",
        "implemented": True,
    },
    {
        "id": "polygon",
        "name": "Polygon.io",
        "cost": "paid",
        "cost_label": "付费为主（有限免费试用）",
        "needs_user_key": True,
        "signup_url": "https://polygon.io",
        "markets": ["us"],
        "notes": "未接入；需要你申请 Key 后可扩展。",
        "implemented": False,
    },
    {
        "id": "finnhub",
        "name": "Finnhub",
        "cost": "freemium",
        "cost_label": "免费档 + 付费",
        "needs_user_key": True,
        "signup_url": "https://finnhub.io",
        "markets": ["us", "global"],
        "notes": "未接入；预留。",
        "implemented": False,
    },
    {
        "id": "wind",
        "name": "Wind 万得",
        "cost": "paid",
        "cost_label": "机构付费",
        "needs_user_key": True,
        "markets": ["ashare", "hk", "us", "fund"],
        "notes": "未接入；需商务授权，不适合默认依赖。",
        "implemented": False,
    },
    {
        "id": "ifind",
        "name": "同花顺 iFinD",
        "cost": "paid",
        "cost_label": "机构付费",
        "needs_user_key": True,
        "markets": ["ashare", "hk", "us", "fund"],
        "notes": "未接入；需商务授权。",
        "implemented": False,
    },
]
